Added new email search engine
edoardottt/awesome-hacker-search-engines pull request #155
Opened 2023-10-21 14:25 UTC by FarukhS52

I have gone through the list of email search engines and added a new search engine that was not there.
Hope it helps.

2023-10-21 16:43 UTC, edoardottt requested changes
requesting small changes

2023-10-21 16:43 UTC, edoardottt commented on README.md
> +- [EmailSearch](https://emailsearch.io/) - Find any emails and phones from a domain, Linkedin, name, and company. Prospect from 600M business contacts and 20M companies.
Please change to:
```
- [EmailSearch.io](https://emailsearch.io/) - Find any emails and phones from a domain, Linkedin, name, and company
```

2023-10-21 17:19 UTC, FarukhS52 commented on README.md
> +- [EmailSearch](https://emailsearch.io/) - Find any emails and phones from a domain, Linkedin, name, and company. Prospect from 600M business contacts and 20M companies.
Okayyy...

2023-10-21 17:24 UTC, FarukhS52 commented
Hey @edoardottt ,i have made the required changes,kindly review this and let me know if any changes are required

2023-10-21 17:24 UTC, FarukhS52 commented
Hey @edoardottt ,i have made the required changes,kindly review this and let me know if any changes are required

2023-10-21 17:27 UTC, FarukhS52 commented
Hey @edoardottt ,i have made the required changes,kindly review this and let me know if any changes are required

2023-10-22 07:38 UTC, edoardottt approved these changes
lgtm

2023-10-22 07:39 UTC, merged