added Cryptome to leaks section
edoardottt/awesome-hacker-search-engines pull request #165
Opened 2023-10-22 09:41 UTC by BkPankaj

Update README.md according to mentioned issue #164

2023-10-22 09:43 UTC, BkPankaj commented
@edoardottt please verify and merge the changes

2023-10-22 10:06 UTC, BkPankaj commented
Added searchftps to code section according to mentioned issue #163 
Please check and merge the request

2023-10-23 06:38 UTC, edoardottt requested changes

2023-10-23 06:38 UTC, edoardottt commented on README.md
> +- [Searchftps](https://www.searchftps.net/) - Online tool for searching and accessing files on FTP servers
Delete this, already handled by https://github.com/edoardottt/awesome-hacker-search-engines/pull/166

2023-10-23 06:38 UTC, edoardottt commented on README.md
> +- [Cryptome](https://cryptome.org/) - Document leaks, government transparency, surveillance information source
The description should be `Documents for publication that are prohibited by governments worldwide`

2023-10-23 06:51 UTC, closed without merging