Update README.md; Added http://metricsparrow.com/toolkit/email-permut…
edoardottt/awesome-hacker-search-engines pull request #175
Opened 2023-10-23 09:21 UTC by idrismusa4

Added Metric Sparrow Email Permutator to email Section. Which Solvevs #160

2023-10-23 09:29 UTC, edoardottt requested changes

2023-10-23 09:29 UTC, edoardottt commented on README.md
> +- [MetricSparrow Email Permutator+](http://metricsparrow.com/toolkit/email-permutator/#) - This tool is intended to help you find the email addresses of people you need to contact by generating poten
Please change to:
```
- [Email Permutator+](http://metricsparrow.com/toolkit/email-permutator/#) - Find potential email addresses permutating different combinations
```

2023-10-23 16:52 UTC, idrismusa4 commented on README.md
> +- [MetricSparrow Email Permutator+](http://metricsparrow.com/toolkit/email-permutator/#) - This tool is intended to help you find the email addresses of people you need to contact by generating poten
Okay done ✅

2023-10-24 07:15 UTC, edoardottt requested changes

2023-10-24 07:15 UTC, edoardottt commented on README.md
> +- [Email Permutator+](http://metricsparrow.com/toolkit/email-permutator/#) - This tool is intended to help you find the email addresses of people you need to contact by generating potential email add
it's not done...
```
- [Email Permutator+](http://metricsparrow.com/toolkit/email-permutator/#) - Find potential email addresses permutating different combinations
```

2023-10-24 07:15 UTC, edoardottt commented on README.md
> +
unnecessary newline

2023-10-24 08:27 UTC, idrismusa4 commented on README.md
> +- [Email Permutator+](http://metricsparrow.com/toolkit/email-permutator/#) - This tool is intended to help you find the email addresses of people you need to contact by generating potential email add
Should be good to go now

2023-10-24 08:32 UTC, edoardottt requested changes

2023-10-24 08:32 UTC, edoardottt commented on README.md
> +- [Email Permutator+](http://metricsparrow.com/toolkit/email-permutator/#) - This tool is intended to help you find the email addresses of people you need to contact by generating potential email add
This is duplicated here, remove it

2023-10-24 08:38 UTC, idrismusa4 commented on README.md
> +- [Email Permutator+](http://metricsparrow.com/toolkit/email-permutator/#) - This tool is intended to help you find the email addresses of people you need to contact by generating potential email add
Okay you can check now

2023-10-24 08:43 UTC, edoardottt approved these changes
lgtm

2023-10-24 08:44 UTC, merged

2023-10-24 08:45 UTC, idrismusa4 commented
> lgtm

Okay then thanks for your revisions