Add Validin to list of free DNS search engines
edoardottt/awesome-hacker-search-engines pull request #194
Opened 2023-10-27 21:27 UTC by warmer

2023-10-28 07:06 UTC, edoardottt requested changes

2023-10-28 07:06 UTC, edoardottt commented on README.md
> +- [Validin](https://app.validin.com/) - Massive collection of DNS records with free DNS history search
Add this at the end of the dns list

2023-10-28 18:38 UTC, warmer commented on README.md
> +- [Validin](https://app.validin.com/) - Massive collection of DNS records with free DNS history search
Fixed

2023-10-29 10:29 UTC, edoardottt approved these changes
lgtm

2023-10-29 10:29 UTC, merged