Added Hudson Rock to Credentials section
edoardottt/awesome-hacker-search-engines pull request #223
Opened 2024-05-16 09:04 UTC by hudsonrock-partnerships

Free cybercrime tools

2024-05-17 07:16 UTC, edoardottt requested changes

2024-05-17 07:16 UTC, edoardottt commented on README.md
> +- [Hudson Rock](https://www.hudsonrock.com/threat-intelligence-cybercrime-tools) - Check if a username, email, or domain was compromised in global Infostealer attacks
Maybe this description would be better: `Use Hudson Rock’s free cybercrime intelligence tools to learn how compromised credentials are impacting your business`

2024-05-17 12:34 UTC, edoardottt commented on README.md
> +- [Hudson Rock](https://www.hudsonrock.com/threat-intelligence-cybercrime-tools) - Check if a username, email, or domain was compromised in global Infostealer attacks
ok, waiting for the changes

2024-05-17 15:51 UTC, hudsonrock-partnerships reviewed
Changed the description

2024-05-18 07:33 UTC, edoardottt approved these changes
lgtm

2024-05-18 07:33 UTC, merged

2024-05-18 07:33 UTC, edoardottt commented
thanks @hudsonrock-partnerships !